/**
 * Turn the cached sources into the committed factual package under `docs/neu/`.
 *
 *   node tools/neu-audit/fetch.mjs && node tools/neu-audit/build.mjs
 *
 * Nothing here is imported by the game. This is evidence preparation: it records
 * what is true about the real Northeastern district and how far the current
 * world is from it, so a later modelling wave starts from measurements rather
 * than from someone's recollection of Huntington Avenue.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { STREETS } from '../../src/data/boston-geo.js';
import { LANDMARKS } from '../../src/data/landmarks.js';
import { geo, segDist, nearestOn, inPoly, osmCentroid, esriCentroid,
         ringCentroid, resample, stats } from './lib.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const CACHE = path.join(HERE, '.cache');
const OUT = path.join(HERE, '../../docs/neu');

if (!fs.existsSync(CACHE)) {
  console.error('no cache — run `node tools/neu-audit/fetch.mjs` first');
  process.exit(1);
}
const load = n => JSON.parse(fs.readFileSync(path.join(CACHE, n), 'utf8'));
const osmRoads = load('roads.json'), osmBuildings = load('buildings.json');
const osmRealm = load('realm.json'), osmTransit = load('transit.json');
const osmAnchors = load('anchors.json'), osmCampus = load('campus.json');
const neuB = load('neu_buildings.json'), neuE = load('neu_entrances.json'), mbta = load('mbta.json');

fs.mkdirSync(OUT, { recursive: true });
const write = (name, obj) => {
  fs.writeFileSync(path.join(OUT, name), JSON.stringify(obj, null, 2) + '\n');
  console.log(`  docs/neu/${name}`);
};
const ATTRIB = {
  osm: 'OpenStreetMap contributors, ODbL 1.0 — https://www.openstreetmap.org/copyright',
  neu: 'Northeastern University ArcGIS Online (services5.arcgis.com/S8KZ4xiwVgqpYP63) — public REST endpoint, terms not separately verified',
  mbta: 'MBTA V3 API — https://api-v3.mbta.com',
};
const GENERATED = 'generated by tools/neu-audit/build.mjs — do not hand-edit';

/* ---------------------------------------------------------------- envelope */
// The campus polygon OSM publishes is the factual seed; the hero core is its
// extent, and the context buffer reaches the streets and stations a player can
// see from inside it.
const campusRing = osmCampus.elements.find(e => e.id === 301210399).geometry.map(q => geo(q.lat, q.lon));
const cx = campusRing.map(p => p.x), cz = campusRing.map(p => p.z);
const core = { x0: Math.min(...cx), x1: Math.max(...cx), z0: Math.min(...cz), z1: Math.max(...cz) };
const BUF = 320;
const buffer = { x0: core.x0 - BUF, x1: core.x1 + BUF, z0: core.z0 - BUF, z1: core.z1 + BUF };
const inCore = p => inPoly(p, campusRing);
const inBuf = p => p.x >= buffer.x0 && p.x <= buffer.x1 && p.z >= buffer.z0 && p.z <= buffer.z1;
const campusCentroid = ringCentroid(campusRing);

/* ----------------------------------------------------------------- anchors */
// How far the world's hand-traced geography sits from the same feature in an
// authoritative source. This is the number that decides whether external GIS
// geometry can be dropped into the existing city or has to replace it.
const anchorPairs = [
  ['faneuil', 'way/29551702', 'Faneuil Hall', 'game entry deliberately covers Faneuil Hall AND Quincy Market'],
  ['stateHouse', 'way/29718019', 'Massachusetts State House', ''],
  ['customHouse', 'way/29719177', 'Custom House Tower', ''],
  ['southStation', 'way/29742438', 'South Station', 'OSM footprint is the whole station; the game pin reads as the head house'],
  ['prudential', 'way/29869880', 'Prudential Tower', ''],
  ['bunkerHill', 'way/212124093', 'Bunker Hill Monument', ''],
  ['oldNorth', 'way/29650592', 'Old North Church', ''],
  ['hancock', 'way/405843558', '200 Clarendon', ''],
  ['bpl', 'relation/63755', 'Boston Public Library', 'game entry names the McKim building only'],
  ['trinity', 'relation/64066', 'Trinity Church', ''],
  ['fenway', 'relation/11188464', 'Fenway Park', ''],
];
const anchors = [];
for (const [id, ref, label, caveat] of anchorPairs) {
  const g = LANDMARKS.find(l => l.id === id);
  const e = osmAnchors.elements.find(x => `${x.type}/${x.id}` === ref);
  if (!g || !e) continue;
  const c = osmCentroid(e); if (!c) continue;
  const gw = geo(g.lat, g.lon);
  const dx = gw.x - c.x, dz = gw.z - c.z;
  anchors.push({ id, label, osmRef: ref, caveat: caveat || undefined,
    gameLatLon: [g.lat, g.lon], gameWorld: [+gw.x.toFixed(1), +gw.z.toFixed(1)],
    osmWorld: [+c.x.toFixed(1), +c.z.toFixed(1)], osmFootprintM2: Math.round(c.area),
    dx: +dx.toFixed(1), dz: +dz.toFixed(1), errorM: +Math.hypot(dx, dz).toFixed(1) });
}
anchors.sort((a, b) => a.errorM - b.errorM);
const clean = anchors.filter(a => !a.caveat);
const bias = { dx: +(anchors.reduce((s, a) => s + a.dx, 0) / anchors.length).toFixed(1),
               dz: +(anchors.reduce((s, a) => s + a.dz, 0) / anchors.length).toFixed(1) };

write('ANCHORS.json', {
  _generated: GENERATED,
  what: 'Game landmark coordinates vs the same feature in OpenStreetMap, both pushed through the game\'s own geo(). Measures how well the hand-authored content matches reality — NOT the projection, which is exact by construction.',
  attribution: ATTRIB.osm,
  projection: { kind: 'equirectangular', originLat: 42.35538, originLon: -71.06565,
                mPerDegLat: 111320, note: 'src/core/Geo.js; content stores real lat/lon and converts at load, so no transform had to be reconstructed' },
  allAnchors: stats(anchors.map(a => a.errorM)),
  definitionCleanAnchors: stats(clean.map(a => a.errorM)),
  systematicBias: { ...bias, magnitudeM: +Math.hypot(bias.dx, bias.dz).toFixed(1),
    reading: 'small next to the per-anchor scatter, so the errors are authoring scatter rather than a rotation, scale or datum fault' },
  anchors,
});

/* -------------------------------------------------------- street geography */
const namedOsmRoads = {};
for (const e of osmRoads.elements) {
  const n = e.tags?.name; if (!n || !e.geometry) continue;
  (namedOsmRoads[n] ||= []).push(e.geometry.map(q => geo(q.lat, q.lon)));
}
// Clip game samples well inside the extract so a sample is never limited by its edge.
const a0 = geo(42.3480, -71.1000), b0 = geo(42.3300, -71.0780);
const clip = { x0: a0.x + 250, z0: a0.z + 250, x1: b0.x - 250, z1: b0.z - 250 };
const deviations = [];
for (const name of ['Huntington Avenue', 'Columbus Avenue', 'Massachusetts Avenue', 'Tremont Street']) {
  const gs = STREETS.filter(s => s.name === name);
  const lines = namedOsmRoads[name];
  if (!gs.length || !lines) continue;
  const ds = [], verts = [];
  for (const s of gs) {
    const pts = s.path.map(([la, lo]) => geo(la, lo));
    for (const p of pts) {
      if (p.x < clip.x0 || p.x > clip.x1 || p.z < clip.z0 || p.z > clip.z1) continue;
      verts.push({ world: [+p.x.toFixed(0), +p.z.toFixed(0)], offsetM: +nearestOn(p, lines).toFixed(0) });
    }
    for (const p of resample(pts, 20)) {
      if (p.x < clip.x0 || p.x > clip.x1 || p.z < clip.z0 || p.z > clip.z1) continue;
      ds.push(nearestOn(p, lines));
    }
  }
  if (ds.length) deviations.push({ street: name, osmWays: lines.length, sampledInEnvelope: ds.length,
                                   offsetFromRealM: stats(ds), verticesInEnvelope: verts });
}

// How much of the campus the game's road graph can actually reach. Parcels — and
// therefore every generic building — are cut from road frontage, so ground with
// no street near it produces no city at all.
const gameLines = STREETS.map(s => ({ name: s.name, pts: s.path.map(([la, lo]) => geo(la, lo)) }));
function nearestGameRoad(p) {
  let best = Infinity, name = null;
  for (const L of gameLines)
    for (let i = 1; i < L.pts.length; i++) {
      const d = segDist(p, L.pts[i - 1], L.pts[i]);
      if (d < best) { best = d; name = L.name; }
    }
  return { d: best, name };
}
const STEP = 10;
const cellD = [], owner = {};
for (let x = core.x0; x <= core.x1; x += STEP)
  for (let z = core.z0; z <= core.z1; z += STEP) {
    const p = { x, z }; if (!inCore(p)) continue;
    const n = nearestGameRoad(p); cellD.push(n.d); owner[n.name] = (owner[n.name] || 0) + 1;
  }
const bands = {};
for (const R of [40, 60, 100, 150, 200, 300])
  bands[`within${R}m`] = +(100 * cellD.filter(d => d <= R).length / cellD.length).toFixed(1);

const realNamed = Object.keys(namedOsmRoads).length;
const gameNamedInEnvelope = new Set();
for (const L of gameLines)
  if (L.pts.some(p => inBuf(p))) gameNamedInEnvelope.add(L.name);

write('GAPS.json', {
  _generated: GENERATED,
  attribution: ATTRIB.osm,
  envelope: {
    heroCoreWorld: { x: [+core.x0.toFixed(0), +core.x1.toFixed(0)], z: [+core.z0.toFixed(0), +core.z1.toFixed(0)] },
    contextBufferWorld: { x: [+buffer.x0.toFixed(0), +buffer.x1.toFixed(0)], z: [+buffer.z0.toFixed(0), +buffer.z1.toFixed(0)] },
    bufferMetres: BUF,
    campusCentroidWorld: [+campusCentroid.x.toFixed(0), +campusCentroid.z.toFixed(0)],
    campusAreaHa: +(campusCentroid.area / 10000).toFixed(1),
    distanceFromBostonCommonM: Math.round(Math.hypot(campusCentroid.x, campusCentroid.z)),
  },
  streetCentrelineDeviation: deviations,
  campusRoadCoverage: {
    what: 'distance from each 10 m cell of the real campus polygon to the nearest road the game actually has',
    cells: cellD.length, distanceM: stats(cellD),
    percentOfCampusWithinBandOfAnyGameRoad: bands,
    nearestGameRoadShare: Object.fromEntries(Object.entries(owner)
      .sort((a, b) => b[1] - a[1]).map(([k, v]) => [k, +(100 * v / cellD.length).toFixed(1)])),
    why: 'RoadNetwork.buildPlots walks road frontage, so campus ground far from any street yields no parcel and no building',
  },
  namedStreets: { realInEnvelope: realNamed, gameInEnvelope: gameNamedInEnvelope.size,
                  gameNames: [...gameNamedInEnvelope].sort() },
});

/* ------------------------------------------------------- building inventory */
const neuBos = neuB.features.filter(f => (f.attributes.Site_ID || '').trim() === 'BOS');
const SQFT = 0.092903;
const osmBldg = osmBuildings.elements
  .filter(e => e.geometry?.length > 2)
  .map(e => ({ tags: e.tags || {}, c: osmCentroid(e) }))
  .filter(b => b.c);

const buildings = neuBos.map(f => {
  const a = f.attributes;
  const c = esriCentroid(f.geometry);
  const name = (a.Name_Long || a.Name || '').replace(/\s+/g, ' ').trim();
  const gross = +a.GrossArea || 0;
  const foot = c ? c.area : 0;
  // Official geometry carries no height and no storey count — both fields are
  // present and uniformly zero. Gross area over footprint is the only figure the
  // official data supports, and because gross area includes below-grade space it
  // is an UPPER BOUND on storeys, not a measurement.
  const impliedStoreys = gross > 0 && foot > 0 ? +((gross * SQFT) / foot).toFixed(1) : null;
  // Nearest OSM building, to pick up a levels tag and to corroborate the position.
  let match = null, best = Infinity;
  for (const b of osmBldg) {
    const d = Math.hypot(b.c.x - c.x, b.c.z - c.z);
    if (d < best) { best = d; match = b; }
  }
  const corroborated = match && best <= 25;
  const osmLevels = corroborated ? +match.tags['building:levels'] || null : null;
  const osmHeight = corroborated ? parseFloat(match.tags.height || match.tags['building:height']) || null : null;
  return {
    name, facilityId: (a.Facility_ID || '').trim() || null,
    address: (a.Address || '').replace(/\s+/g, ' ').trim() || null,
    yearBuilt: (a.YearBuilt || '').trim() || null,
    yearRenovated: (a.YearReno || '').trim() || null,
    ownership: (a.Ownership || '').trim() || null,
    grossAreaSqFt: gross || null,
    footprintM2: Math.round(foot),
    worldXZ: [Math.round(c.x), Math.round(c.z)],
    onCampusPolygon: inCore(c),
    storeys: { osmLevels, impliedFromGrossArea: impliedStoreys,
               confidence: osmLevels ? 'C' : impliedStoreys ? 'D' : 'UNKNOWN' },
    heightM: { osmTagged: osmHeight, confidence: osmHeight ? 'C' : 'UNKNOWN',
               note: osmHeight ? undefined : 'no height in either official or open data; must be surveyed or inferred at modelling time' },
    osmCrossCheck: corroborated
      ? { matchedName: match.tags.name || null, centroidAgreementM: +best.toFixed(1) }
      : { matchedName: null, centroidAgreementM: +best.toFixed(1), note: 'no OSM footprint within 25 m' },
    footprintConfidence: corroborated ? 'B' : 'A',
  };
}).filter(b => b.name);

// Priority classes, assigned by rule rather than by taste, so the ranking can be
// re-derived and argued with. Distances are to the two arrival sequences the
// player will actually use.
const KRENTZMAN = { x: -1865, z: 1699 };          // OSM leisure=park, Krentzman Quadrangle
const RUGGLES_FORSYTH = { x: -1955, z: 2045 };    // MBTA door-rugg-forsyth, "Northeastern, Forsyth St"
const HUNTINGTON = namedOsmRoads['Huntington Avenue'];
for (const b of buildings) {
  const p = { x: b.worldXZ[0], z: b.worldXZ[1] };
  const dHunt = nearestOn(p, HUNTINGTON);
  const dK = Math.hypot(p.x - KRENTZMAN.x, p.z - KRENTZMAN.z);
  const dR = Math.hypot(p.x - RUGGLES_FORSYTH.x, p.z - RUGGLES_FORSYTH.z);
  const tall = (b.storeys.osmLevels || b.storeys.impliedFromGrossArea || 0) >= 8;
  let cls, why;
  if (b.onCampusPolygon && (dHunt <= 70 || dK <= 130 || dR <= 130)) {
    cls = 'HERO_A'; why = `on the arrival sequence (Huntington ${Math.round(dHunt)} m, Krentzman ${Math.round(dK)} m, Ruggles/Forsyth ${Math.round(dR)} m)`;
  } else if (b.onCampusPolygon && tall) {
    cls = 'HERO_B'; why = 'campus-scale mass — reads as a navigation anchor above the fabric';
  } else if (b.onCampusPolygon) {
    cls = 'CONTEXT_C'; why = 'named campus building away from the arrival sequence';
  } else {
    cls = 'BACKGROUND_D'; why = 'university-held building outside the campus polygon';
  }
  b.priority = cls;
  b.priorityBasis = why;
  b.distances = { huntingtonM: Math.round(dHunt), krentzmanM: Math.round(dK), rugglesForsythM: Math.round(dR) };
}
buildings.sort((a, b) => (a.priority.localeCompare(b.priority)) || b.footprintM2 - a.footprintM2);
const classCount = buildings.reduce((a, b) => (a[b.priority] = (a[b.priority] || 0) + 1, a), {});

write('BUILDING_INVENTORY.json', {
  _generated: GENERATED,
  what: 'Real Northeastern Boston buildings. Footprints, names, year built and gross area are official; storeys and heights are not published by the official source and are marked accordingly.',
  attribution: [ATTRIB.neu, ATTRIB.osm],
  confidenceKey: { A: 'official geometry/attribute', B: 'official, corroborated by an independent open source',
                   C: 'single open-data source (OSM)', D: 'inferred — basis stated', UNKNOWN: 'unresolved' },
  priorityKey: {
    HERO_A: 'must be recognisable at eye level on the arrival sequence',
    HERO_B: 'campus identity / navigation anchor',
    CONTEXT_C: 'credible massing and materials, no bespoke detail initially',
    BACKGROUND_D: 'procedural representation acceptable if footprint and scale are right',
  },
  counts: { officialBostonBuildings: neuBos.length, named: buildings.length,
            insideCampusPolygon: buildings.filter(b => b.onCampusPolygon).length, byPriority: classCount },
  heightAvailability: {
    officialLevelsAboveGround: 0, officialHeightRelative: 0,
    osmLevelsTagged: buildings.filter(b => b.storeys.osmLevels).length,
    osmHeightTagged: buildings.filter(b => b.heightM.osmTagged).length,
    note: 'The official Buildings_ALL layer publishes Levels_Above_Ground and Height_Relative for every Boston row as 0. Heights are the single biggest factual hole in this package.',
  },
  buildings,
});

/* ------------------------------------------------------------ public realm */
let footM = 0, footWays = 0, stepWays = 0, pedWays = 0;
const spaces = [];
for (const e of osmRealm.elements) {
  const t = e.tags || {}, g = e.geometry; if (!g?.length) continue;
  const c = osmCentroid(e); if (!c) continue;
  const on = inCore(c);
  if (!on) continue;
  if (t.highway === 'footway' || t.highway === 'path') {
    footWays++;
    const w = g.map(q => geo(q.lat, q.lon));
    for (let i = 1; i < w.length; i++) footM += Math.hypot(w[i].x - w[i - 1].x, w[i].z - w[i - 1].z);
  }
  if (t.highway === 'steps') stepWays++;
  if (t.highway === 'pedestrian') pedWays++;
  const kind = t.leisure ? `leisure=${t.leisure}` : t.landuse ? `landuse=${t.landuse}` : t.place ? `place=${t.place}` : null;
  if (t.name && kind && c.area > 100)
    spaces.push({ name: t.name, kind, areaM2: Math.round(c.area), worldXZ: [Math.round(c.x), Math.round(c.z)], confidence: 'C' });
}
spaces.sort((a, b) => b.areaM2 - a.areaM2);
const officialEntrances = (neuE.features || [])
  .map(f => ({ name: (f.attributes.Name || f.attributes.Label || '').trim(), p: geo(f.geometry.y, f.geometry.x) }))
  .filter(e => inBuf(e.p))
  .map(e => ({ name: e.name, worldXZ: [Math.round(e.p.x), Math.round(e.p.z)], confidence: 'A' }));

write('PUBLIC_REALM.json', {
  _generated: GENERATED,
  what: 'The campus outdoor room. Eye-level identity here rests at least as much on these spaces and the walking network as on the buildings.',
  attribution: [ATTRIB.osm, ATTRIB.neu],
  pedestrianNetworkOnCampus: { footwayAndPathWays: footWays, footwayMetres: Math.round(footM),
                               stepsWays: stepWays, pedestrianStreetWays: pedWays, confidence: 'C',
                               note: 'the 39 stair runs are the clearest evidence that campus grade changes are local and structural rather than a broad slope' },
  namedSpaces: spaces,
  officialAccessibleEntrances: { count: officialEntrances.length, confidence: 'A', points: officialEntrances },
});

/* ----------------------------------------------------------------- transit */
const stations = [], entrances = [];
for (const s of mbta.data || []) {
  const a = s.attributes; if (a.latitude == null) continue;
  const p = geo(a.latitude, a.longitude);
  if (!inBuf(p)) continue;
  const row = { id: s.id, name: a.name, worldXZ: [Math.round(p.x), Math.round(p.z)],
                latLon: [a.latitude, a.longitude], platform: a.platform_name || null, confidence: 'A' };
  if (a.location_type === 1) stations.push(row);
  if (a.location_type === 2) entrances.push(row);
}
const rail = {};
for (const e of osmTransit.elements) {
  if (e.type !== 'way' || !e.geometry) continue;
  const k = e.tags?.railway; if (!k) continue;
  const w = e.geometry.map(q => geo(q.lat, q.lon));
  let L = 0, near = Infinity;
  for (let i = 0; i < w.length; i++) {
    near = Math.min(near, Math.hypot(w[i].x - campusCentroid.x, w[i].z - campusCentroid.z));
    if (i) L += Math.hypot(w[i].x - w[i - 1].x, w[i].z - w[i - 1].z);
  }
  rail[k] ||= { ways: 0, metres: 0, closestToCampusM: Infinity };
  rail[k].ways++; rail[k].metres += L; rail[k].closestToCampusM = Math.min(rail[k].closestToCampusM, near);
}
for (const k of Object.keys(rail)) {
  rail[k].metres = Math.round(rail[k].metres);
  rail[k].closestToCampusM = Math.round(rail[k].closestToCampusM);
}
write('TRANSIT.json', {
  _generated: GENERATED,
  what: 'Transit context for the hero district. The game currently represents no rail transit of any kind — no station, no alignment, no surface trolley.',
  attribution: [ATTRIB.mbta, ATTRIB.osm],
  stations: stations.sort((a, b) => a.name.localeCompare(b.name)),
  stationEntrances: entrances.sort((a, b) => a.name.localeCompare(b.name)),
  railAlignments: rail,
  gameRepresentation: { railStations: 0, railAlignments: 0, surfaceTrolley: false,
                        present: 'MBTA buses, bus stops and a "T" roundel sign only' },
});

console.log(`\n${buildings.length} named buildings, ${spaces.length} named spaces, ${stations.length} stations`);

/* -------------------------------------------------- arrival / spawn candidates */
// Deliberately NOT a single answer. Northeastern's own material calls Krentzman
// "one of the campus' primary gateways" — one of several — and the busiest real
// arrival is a transit interchange, not a gate. The final pick is an owner
// art/product decision; this table is the evidence for making it.
const CANDIDATES = [
  { id: 'krentzman', name: 'Krentzman Quadrangle / 360 Huntington Avenue', world: [-1865, 1699],
    identity: 'The ceremonial front door. Original campus nucleus from the 1934 invitational competition; Ell, Richards and Dodge halls front onto it; the brick ledge carrying the university seal is the graduation photo spot. 360 Huntington Avenue is the university\'s published address.',
    against: 'A quadrangle, not a forecourt — the space opens off the pavement, so a vehicle cannot stand in it without inventing a driveway.' },
  { id: 'ruggles', name: 'Ruggles station / Forsyth Street', world: [-1955, 2045],
    identity: 'The busiest real arrival: Orange Line, commuter rail and a nine-berth busway. The MBTA\'s own entrance here is named "Northeastern, Forsyth St".',
    against: 'Reads as a transit interchange rather than as a university; the station structure and its rail cut are heavy modelling before the district looks like anything.' },
  { id: 'centennial', name: 'Centennial Common', world: [-2032, 2038],
    identity: 'The largest enclosed green inside the campus and its ceremonial heart.',
    against: 'Interior. No street frontage at all, so neither a car nor a credible first camera shot belongs here.' },
  { id: 'isec', name: 'ISEC / Columbus Avenue', world: [-1750, 1970],
    identity: 'The newest identity of the university — the science complex and the pedestrian crossing over the rail corridor.',
    against: 'Across the tracks from the historic campus; recognisable to people who know the place now, not to a general audience.' },
];
const realRoadLines = Object.values(namedOsmRoads).flat();
const spawnCandidates = CANDIDATES.map(c => {
  const p = { x: c.world[0], z: c.world[1] };
  const ll = { lat: 42.35538 - p.z / 111320, lon: -71.06565 + p.x / (111320 * Math.cos(42.35538 * Math.PI / 180)) };
  const gameRoad = nearestGameRoad(p);
  const nearest = buildings
    .map(b => ({ n: b.name, d: Math.round(Math.hypot(b.worldXZ[0] - p.x, b.worldXZ[1] - p.z)) }))
    .sort((a, b) => a.d - b.d).slice(0, 4);
  const st = [...stations, ...entrances]
    .map(s => ({ n: s.name, d: Math.round(Math.hypot(s.worldXZ[0] - p.x, s.worldXZ[1] - p.z)) }))
    .sort((a, b) => a.d - b.d).slice(0, 3);
  return { ...c, realLatLon: [+ll.lat.toFixed(6), +ll.lon.toFixed(6)],
    realRoadDistanceM: Math.round(nearestOn(p, realRoadLines)),
    todayNearestGameRoad: { name: gameRoad.name, distanceM: Math.round(gameRoad.d) },
    nearestBuildings: nearest, nearestTransit: st };
});
write('SPAWN_CANDIDATES.json', {
  _generated: GENERATED,
  what: 'Candidate locations for the eventual canonical player spawn and starting SUV. NOT a decision — the spawn does not move until the migration gate in docs/neu/CURRENT_VS_REAL.md passes.',
  attribution: [ATTRIB.neu, ATTRIB.mbta, ATTRIB.osm],
  finding: 'Authoritative material does not support one singular "main gate". The university calls Krentzman one of its primary gateways, and the heaviest real arrival is Ruggles. This is case C: an urban-campus arrival space rather than a conventional gate.',
  currentSpawnWorld: [166, 128],
  currentSpawnToCampusM: Math.round(Math.hypot(166 - campusCentroid.x, 128 - campusCentroid.z)),
  candidates: spawnCandidates,
});
